/**
 * This file is autogenerated from Foundry deployments.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  31337: {
    MockPyth: {
      address: "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_validTimePeriod",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_singleUpdateFeeInWei",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createPriceFeedUpdateData",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "price",
              type: "int64",
              internalType: "int64",
            },
            {
              name: "conf",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "expo",
              type: "int32",
              internalType: "int32",
            },
            {
              name: "emaPrice",
              type: "int64",
              internalType: "int64",
            },
            {
              name: "emaConf",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "publishTime",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "prevPublishTime",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          outputs: [
            {
              name: "priceFeedData",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "createTwapPriceFeedUpdateData",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "startTime",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "endTime",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "price",
              type: "int64",
              internalType: "int64",
            },
            {
              name: "conf",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "expo",
              type: "int32",
              internalType: "int32",
            },
            {
              name: "downSlotsRatio",
              type: "uint32",
              internalType: "uint32",
            },
          ],
          outputs: [
            {
              name: "twapData",
              type: "bytes",
              internalType: "bytes",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "getEmaPrice",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "price",
              type: "tuple",
              internalType: "struct PythStructs.Price",
              components: [
                {
                  name: "price",
                  type: "int64",
                  internalType: "int64",
                },
                {
                  name: "conf",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "expo",
                  type: "int32",
                  internalType: "int32",
                },
                {
                  name: "publishTime",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEmaPriceNoOlderThan",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "age",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "price",
              type: "tuple",
              internalType: "struct PythStructs.Price",
              components: [
                {
                  name: "price",
                  type: "int64",
                  internalType: "int64",
                },
                {
                  name: "conf",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "expo",
                  type: "int32",
                  internalType: "int32",
                },
                {
                  name: "publishTime",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getEmaPriceUnsafe",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "price",
              type: "tuple",
              internalType: "struct PythStructs.Price",
              components: [
                {
                  name: "price",
                  type: "int64",
                  internalType: "int64",
                },
                {
                  name: "conf",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "expo",
                  type: "int32",
                  internalType: "int32",
                },
                {
                  name: "publishTime",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPrice",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "price",
              type: "tuple",
              internalType: "struct PythStructs.Price",
              components: [
                {
                  name: "price",
                  type: "int64",
                  internalType: "int64",
                },
                {
                  name: "conf",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "expo",
                  type: "int32",
                  internalType: "int32",
                },
                {
                  name: "publishTime",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPriceNoOlderThan",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "age",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "price",
              type: "tuple",
              internalType: "struct PythStructs.Price",
              components: [
                {
                  name: "price",
                  type: "int64",
                  internalType: "int64",
                },
                {
                  name: "conf",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "expo",
                  type: "int32",
                  internalType: "int32",
                },
                {
                  name: "publishTime",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPriceUnsafe",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "price",
              type: "tuple",
              internalType: "struct PythStructs.Price",
              components: [
                {
                  name: "price",
                  type: "int64",
                  internalType: "int64",
                },
                {
                  name: "conf",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "expo",
                  type: "int32",
                  internalType: "int32",
                },
                {
                  name: "publishTime",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTwapUpdateFee",
          inputs: [
            {
              name: "updateData",
              type: "bytes[]",
              internalType: "bytes[]",
            },
          ],
          outputs: [
            {
              name: "feeAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUpdateFee",
          inputs: [
            {
              name: "updateData",
              type: "bytes[]",
              internalType: "bytes[]",
            },
          ],
          outputs: [
            {
              name: "feeAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getValidTimePeriod",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "parsePriceFeedUpdates",
          inputs: [
            {
              name: "updateData",
              type: "bytes[]",
              internalType: "bytes[]",
            },
            {
              name: "priceIds",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
            {
              name: "minPublishTime",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "maxPublishTime",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          outputs: [
            {
              name: "feeds",
              type: "tuple[]",
              internalType: "struct PythStructs.PriceFeed[]",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "price",
                  type: "tuple",
                  internalType: "struct PythStructs.Price",
                  components: [
                    {
                      name: "price",
                      type: "int64",
                      internalType: "int64",
                    },
                    {
                      name: "conf",
                      type: "uint64",
                      internalType: "uint64",
                    },
                    {
                      name: "expo",
                      type: "int32",
                      internalType: "int32",
                    },
                    {
                      name: "publishTime",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "emaPrice",
                  type: "tuple",
                  internalType: "struct PythStructs.Price",
                  components: [
                    {
                      name: "price",
                      type: "int64",
                      internalType: "int64",
                    },
                    {
                      name: "conf",
                      type: "uint64",
                      internalType: "uint64",
                    },
                    {
                      name: "expo",
                      type: "int32",
                      internalType: "int32",
                    },
                    {
                      name: "publishTime",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "parsePriceFeedUpdatesUnique",
          inputs: [
            {
              name: "updateData",
              type: "bytes[]",
              internalType: "bytes[]",
            },
            {
              name: "priceIds",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
            {
              name: "minPublishTime",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "maxPublishTime",
              type: "uint64",
              internalType: "uint64",
            },
          ],
          outputs: [
            {
              name: "feeds",
              type: "tuple[]",
              internalType: "struct PythStructs.PriceFeed[]",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "price",
                  type: "tuple",
                  internalType: "struct PythStructs.Price",
                  components: [
                    {
                      name: "price",
                      type: "int64",
                      internalType: "int64",
                    },
                    {
                      name: "conf",
                      type: "uint64",
                      internalType: "uint64",
                    },
                    {
                      name: "expo",
                      type: "int32",
                      internalType: "int32",
                    },
                    {
                      name: "publishTime",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "emaPrice",
                  type: "tuple",
                  internalType: "struct PythStructs.Price",
                  components: [
                    {
                      name: "price",
                      type: "int64",
                      internalType: "int64",
                    },
                    {
                      name: "conf",
                      type: "uint64",
                      internalType: "uint64",
                    },
                    {
                      name: "expo",
                      type: "int32",
                      internalType: "int32",
                    },
                    {
                      name: "publishTime",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "parsePriceFeedUpdatesWithConfig",
          inputs: [
            {
              name: "updateData",
              type: "bytes[]",
              internalType: "bytes[]",
            },
            {
              name: "priceIds",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
            {
              name: "minAllowedPublishTime",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "maxAllowedPublishTime",
              type: "uint64",
              internalType: "uint64",
            },
            {
              name: "checkUniqueness",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "checkUpdateDataIsMinimal",
              type: "bool",
              internalType: "bool",
            },
            {
              name: "storeUpdatesIfFresh",
              type: "bool",
              internalType: "bool",
            },
          ],
          outputs: [
            {
              name: "feeds",
              type: "tuple[]",
              internalType: "struct PythStructs.PriceFeed[]",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "price",
                  type: "tuple",
                  internalType: "struct PythStructs.Price",
                  components: [
                    {
                      name: "price",
                      type: "int64",
                      internalType: "int64",
                    },
                    {
                      name: "conf",
                      type: "uint64",
                      internalType: "uint64",
                    },
                    {
                      name: "expo",
                      type: "int32",
                      internalType: "int32",
                    },
                    {
                      name: "publishTime",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "emaPrice",
                  type: "tuple",
                  internalType: "struct PythStructs.Price",
                  components: [
                    {
                      name: "price",
                      type: "int64",
                      internalType: "int64",
                    },
                    {
                      name: "conf",
                      type: "uint64",
                      internalType: "uint64",
                    },
                    {
                      name: "expo",
                      type: "int32",
                      internalType: "int32",
                    },
                    {
                      name: "publishTime",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
            {
              name: "slots",
              type: "uint64[]",
              internalType: "uint64[]",
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "parseTwapPriceFeedUpdates",
          inputs: [
            {
              name: "updateData",
              type: "bytes[]",
              internalType: "bytes[]",
            },
            {
              name: "priceIds",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
          ],
          outputs: [
            {
              name: "twapPriceFeeds",
              type: "tuple[]",
              internalType: "struct PythStructs.TwapPriceFeed[]",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "startTime",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "endTime",
                  type: "uint64",
                  internalType: "uint64",
                },
                {
                  name: "twap",
                  type: "tuple",
                  internalType: "struct PythStructs.Price",
                  components: [
                    {
                      name: "price",
                      type: "int64",
                      internalType: "int64",
                    },
                    {
                      name: "conf",
                      type: "uint64",
                      internalType: "uint64",
                    },
                    {
                      name: "expo",
                      type: "int32",
                      internalType: "int32",
                    },
                    {
                      name: "publishTime",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "downSlotsRatio",
                  type: "uint32",
                  internalType: "uint32",
                },
              ],
            },
          ],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "priceFeedExists",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "queryPriceFeed",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "priceFeed",
              type: "tuple",
              internalType: "struct PythStructs.PriceFeed",
              components: [
                {
                  name: "id",
                  type: "bytes32",
                  internalType: "bytes32",
                },
                {
                  name: "price",
                  type: "tuple",
                  internalType: "struct PythStructs.Price",
                  components: [
                    {
                      name: "price",
                      type: "int64",
                      internalType: "int64",
                    },
                    {
                      name: "conf",
                      type: "uint64",
                      internalType: "uint64",
                    },
                    {
                      name: "expo",
                      type: "int32",
                      internalType: "int32",
                    },
                    {
                      name: "publishTime",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
                {
                  name: "emaPrice",
                  type: "tuple",
                  internalType: "struct PythStructs.Price",
                  components: [
                    {
                      name: "price",
                      type: "int64",
                      internalType: "int64",
                    },
                    {
                      name: "conf",
                      type: "uint64",
                      internalType: "uint64",
                    },
                    {
                      name: "expo",
                      type: "int32",
                      internalType: "int32",
                    },
                    {
                      name: "publishTime",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "updatePriceFeeds",
          inputs: [
            {
              name: "updateData",
              type: "bytes[]",
              internalType: "bytes[]",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "updatePriceFeedsIfNecessary",
          inputs: [
            {
              name: "updateData",
              type: "bytes[]",
              internalType: "bytes[]",
            },
            {
              name: "priceIds",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
            {
              name: "publishTimes",
              type: "uint64[]",
              internalType: "uint64[]",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "event",
          name: "PriceFeedUpdate",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "publishTime",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
            {
              name: "price",
              type: "int64",
              indexed: false,
              internalType: "int64",
            },
            {
              name: "conf",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "TwapPriceFeedUpdate",
          inputs: [
            {
              name: "id",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "startTime",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
            {
              name: "endTime",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
            {
              name: "twapPrice",
              type: "int64",
              indexed: false,
              internalType: "int64",
            },
            {
              name: "twapConf",
              type: "uint64",
              indexed: false,
              internalType: "uint64",
            },
            {
              name: "downSlotsRatio",
              type: "uint32",
              indexed: false,
              internalType: "uint32",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "InsufficientFee",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidArgument",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidTwapUpdateDataSet",
          inputs: [],
        },
        {
          type: "error",
          name: "NoFreshUpdate",
          inputs: [],
        },
        {
          type: "error",
          name: "PriceFeedNotFound",
          inputs: [],
        },
        {
          type: "error",
          name: "PriceFeedNotFoundWithinRange",
          inputs: [],
        },
        {
          type: "error",
          name: "StalePrice",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
    },
    MockERC20: {
      address: "0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "symbol",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "ERC20InsufficientAllowance",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InsufficientBalance",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSpender",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
    },
    DecentralizedStableCoin: {
      address: "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9",
      abi: [
        {
          type: "constructor",
          inputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "allowance",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "approve",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "balanceOf",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "burn",
          inputs: [
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "burnFrom",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "decimals",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "mint",
          inputs: [
            {
              name: "_to",
              type: "address",
              internalType: "address",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "name",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "symbol",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "string",
              internalType: "string",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transfer",
          inputs: [
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferFrom",
          inputs: [
            {
              name: "from",
              type: "address",
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Approval",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "spender",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Transfer",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "value",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "DecentralizedStableCoin__BurnAmountExceedsBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "DecentralizedStableCoin__MustBeMoreThanZero",
          inputs: [],
        },
        {
          type: "error",
          name: "DecentralizedStableCoin__NotZeroAddress",
          inputs: [],
        },
        {
          type: "error",
          name: "ERC20InsufficientAllowance",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
            {
              name: "allowance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InsufficientBalance",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
            {
              name: "balance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "needed",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidApprover",
          inputs: [
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidReceiver",
          inputs: [
            {
              name: "receiver",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSender",
          inputs: [
            {
              name: "sender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "ERC20InvalidSpender",
          inputs: [
            {
              name: "spender",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
    },
    DSCEngine: {
      address: "0x5fc8d32690cc91d4c39d9d3abcbd16989f875707",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_pythContract",
              type: "address",
              internalType: "address",
            },
            {
              name: "_dscAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_colalteralTokens",
              type: "address[]",
              internalType: "address[]",
            },
            {
              name: "_priceFeeds",
              type: "bytes32[]",
              internalType: "bytes32[]",
            },
            {
              name: "_pythMaxAge",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "burnDsc",
          inputs: [
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "burnDscAndWithdrawCollateral",
          inputs: [
            {
              name: "_collateralTokenAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_amountCollateral",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_amountDsc",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "calculateHealthFactor",
          inputs: [
            {
              name: "_dscBalance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_collateralValue",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "pure",
        },
        {
          type: "function",
          name: "depositCollateral",
          inputs: [
            {
              name: "_collateralTokenAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "depositCollateralAndMintDsc",
          inputs: [
            {
              name: "_collateralTokenAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_collateralAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_dscAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getAccountInformation",
          inputs: [
            {
              name: "_user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "dscBalance",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "collateralValue",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCollateralDepositedOfUser",
          inputs: [
            {
              name: "_user",
              type: "address",
              internalType: "address",
            },
            {
              name: "_collateralToken",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCollateralTokenPriceFeed",
          inputs: [
            {
              name: "_collateralToken",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCollateralTokens",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address[]",
              internalType: "address[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getCollateralValue",
          inputs: [
            {
              name: "_user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "totalCollateralValue",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDscMinted",
          inputs: [
            {
              name: "_user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getHealthFactor",
          inputs: [
            {
              name: "_user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPrice",
          inputs: [
            {
              name: "_collateralToken",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPythAddress",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTokenAmountFromUsd",
          inputs: [
            {
              name: "_collateralToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdAmountInWei",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getTotalSupply",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUsdValue",
          inputs: [
            {
              name: "_collateralToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "liquidate",
          inputs: [
            {
              name: "_collateralTokenAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_user",
              type: "address",
              internalType: "address",
            },
            {
              name: "_debtToCover",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "mintDsc",
          inputs: [
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "withdrawCollateral",
          inputs: [
            {
              name: "_collateralTokenAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "CollateralDeposited",
          inputs: [
            {
              name: "user",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "CollateralWithdrawn",
          inputs: [
            {
              name: "redeemedFrom",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "redeemedTo",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "token",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "DSCEngine__AllowanceExceedsBalance",
          inputs: [],
        },
        {
          type: "error",
          name: "DSCEngine__AmountShouldBeMoreThanZero",
          inputs: [],
        },
        {
          type: "error",
          name: "DSCEngine__CollateralTokenNotSupported",
          inputs: [],
        },
        {
          type: "error",
          name: "DSCEngine__ConstructorMissmatchArrayLength",
          inputs: [],
        },
        {
          type: "error",
          name: "DSCEngine__HealthFactorIsFine",
          inputs: [],
        },
        {
          type: "error",
          name: "DSCEngine__HealthFactorIsTooLow",
          inputs: [],
        },
        {
          type: "error",
          name: "DSCEngine__HealthNotImproved",
          inputs: [],
        },
        {
          type: "error",
          name: "DSCEngine__MintFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "DSCEngine__TransferFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts;
